name: Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run generate
            - run: npm run build
              env:
                  AUTH_CA: ${{secrets.AUTH_CA}}
                  AUTH_KEY: ${{secrets.AUTH_KEY}}
                  AUTH_CERT: ${{secrets.AUTH_CERT}}
